# A simple action usage
name: neko kernel lite
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: neko kernel lite
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/D3nesyan/android_kernel_xiaomi_lavender
          kernel-dir: main
          kernel-branch: ruby
          config: cas_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: 0.7.6
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          anykernel3: true
